server:
   port: 8081
spring:
   profiles:
      active: ${SPRING_PROFILES_ACTIVE:dev}
   config:
      import: 'optional:configserver:'
      cloud:
         config:
            uri: http://${URL_CONFIG_SERVER:localhost}:8888/
   application:
      name: authentication